apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: voting-app-namespace
  labels:
    app: demo-voting-app
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::<account-id>:role/nodes.dev.k8s.local
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: demo-voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-voting-app

    spec:
      containers:
      - name: postgres
        image: <account-id>.dkr.ecr.us-east-1.amazonaws.com/voting-app-namespace/postgres
        ports:
        - containerPort: 5432
