apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  namespace: voting-app-namespace
  labels:
    app: demo-voting-app
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::<account-id>:role/nodes.dev.k8s.local
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app

    spec:
      containers:
      - name: result-app
        image: <account-id>.dkr.ecr.us-east-1.amazonaws.com/voting-app-namespace/result:latest
        ports:
                - containerPort: 80
