apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  namespace: voting-app-namespace
  labels:
    app: demo-voting-app
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::<account-id>:role/nodes.dev.k8s.local
spec:
  replicas: 3
  selector:
    matchLabels:
      name: voting-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: demo-voting-app

    spec:
      containers:
      - name: voting-app
        image: <account-id>.dkr.ecr.us-east-1.amazonaws.com/voting-app-namespace/vote:latest
        ports:
        - containerPort: 80
