apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  namespace: voting-app-namespace
  labels:
    app: demo-voting-app
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::<account-id>:role/nodes.dev.k8s.local
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app

    spec:
      containers:
      - name: worker-app
        image: <account-id>.dkr.ecr.us-east-1.amazonaws.com/voting-app-namespace/worker
